name: Builder

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build all apps
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
    
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      
      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn build
        env:
          # pass placehoder env vars to the build script to avoid errors while validating env vars of UI app
          NEXTAUTH_SECRET: only_for_build_so_this_can_be_public
          NEXTAUTH_URL: http://localhost:3000
          NEXT_PUBLIC_APP_PUBLIC_URL: http://localhost:3000
          NEXT_PUBLIC_STRAPI_URL: http://127.0.0.1:1337


